### ISSUE TITLE
[1.16-pre2] Server crash on start

### ISSUE THREAD

**Issue by kwpugh** [SynthRose/art-of-alchemy#27]
Log:  https://gist.github.com/kwpugh/2a99dc2dd144f8867c6ff54b52005817

**Comment by SynthRose** [comment]
Heh, and this is why we test on dedicated servers before releasing, even if it's just a version port. Sorry I didn't see this issue earlier, unfortunately I didn't see the email!

Fixed in 0.7.0.1.

**Comment by kwpugh** [comment]
Thanks.
