### ISSUE TITLE
REI support for machines

### ISSUE THREAD

**Issue by Lykrast** [SynthRose/art-of-alchemy#33]
*(disclaimer I only did limited testing with the mod)*

Since it seems like not all items can be calcinated/dissolved/synthesized it would be nice to have support for those machines (and any that I missed) in REI so that you can easily look up things like:

* What can be calcinated/dissolved/synthesized
* What do you need to synthesize something (that's easily checked on the table itself but it's good to see everything in one place)
* What are good sources of materia/essentia
* What can you do with spare essentia

**Comment by SynthRose** [comment]
Definitely something I'd like to have, although I haven't really looked into the API yet.

**Comment by ghost** [comment]
Art of Alchemy is now being maintained by a different team in a new repository. Please use https://github.com/Cumulus-Mods/Art-of-Alchemy/issues/8 for further discussion on this issue. Thank you.
