### ISSUE TITLE
Synthesis Table Issues

### ISSUE THREAD

**Issue by alexzander700** [SynthRose/art-of-alchemy#34]
Essentially, Materia doesn't work in the Synthesis Table. I have been trying to make a philosopher's stone for an hour, and it won't accept any amount of materia. I have tried using all types of materia from Tier A downwards, and nothing is working.

**Comment by SynthRose** [comment]
> I have tried using all types of materia from Tier A downwards, and nothing is working.
Well there's your problem - the Philosopher's Stone requires Tier S materia ;)

**Comment by SynthRose** [comment]
[PHILOSOPHER'S STONE SPOILERS FOLLOW]
The part of the Philosopher's Stone recipe that occurs in the Synthesis Table does not use materia dust, but rather an Activated Amaranth Pearl.

**Comment by alexzander700** [comment]
According to the GitHub Wiki, the Synthesis Table only accepts up to C Tier Materia, so how do you get S Tier to work in a max of C?

**Comment by alexzander700** [comment]
How do you get the cracked Amaranth Pearl? I've tried everything, but not cheating it in.

**Comment by SynthRose** [comment]
Try placing an Amaranth Pearl into a Calcination Furnace.
